check CLANG_PATH is not a directory BEFORE trying to execute it
If $CLANG_PATH is set, but doesn't point to a clang binary (but say, the
source code directory of clang) bindgen will fail with cryptic errors
pointing back to clang-sys:

  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
  "could not run executable `/llvm-project/clang`: Permission denied (os
  error 13)"',
  ~/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.0.3/src/support.rs:165:58

Check this env var points to an executable file or ignore it.

Fixes #138